default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: photo_manager_development

test:
  <<: *default
  database: photo_manager_test

production:
  <<: *default
  database: photo_manager_production
